### ISSUE TITLE
Is it possible to model outages of variable generation?

### ISSUE THREAD

**Issue by ianfiske** [NREL/ResourceAdequacy.jl#35]
Since VG is modeled differently from regular generators, as a time series of MW, it does not include the μ and λ outage parameters that storage and dispatchable generators have.  Is there a recommended way to model random outages in VG?

**Comment by GordStephen** [comment]
As of right now, the best option is probably just to define the VG as a dispatchable generator with time-varying capacity. I suspect memory consumption will be less-than-desirable under that approach, though. Generator unit representations are going to be reworked in v0.5, this use-case should definitely be considered in that process.

**Comment by GordStephen** [comment]
Closing now that #40 is merged - VG is now treated the same as other generator types and can have outage rates.
