### ISSUE TITLE
Storage attached to specific VG

### ISSUE THREAD

**Issue by ianfiske** [NREL/ResourceAdequacy.jl#36]
A common construction is to have storage attached to solar behind the inverter in order to capture clipped energy from overbuilt farms or just to temporally shift energy to meet the load.  Is there a recommended way to model this in PRAS?

Maybe adjust the MW time series for that solar farm that becomes solar + battery and then do not incorporate this battery in the `StorageDeviceSpec`s?

**Comment by GordStephen** [comment]
Yeah, for now the best solution would be to bake in the storage dispatch into the VG profile. But an explicit representation is on the to-do list for the 0.5 unit representation rework  (#24)

**Comment by GordStephen** [comment]
Closing now that #40 is merged - VG + storage can be represented as a GeneratorStorage device

**Comment by juliebuard** [comment]
Great!! Thanks a lot Gord!
