### ISSUE TITLE
REPRA's `window_idxs` always returns all indexes

### ISSUE THREAD

**Issue by ianfiske** [NREL/ResourceAdequacy.jl#37]
https://github.com/NREL/ResourceAdequacy.jl/blob/43032d6fa2062586110c0bd41328f5002fe2c6c1/src/extractions/repra.jl#L56

Seems like there's a missing `if` statement?

It appears that it should return just the indices specified by the window hour and day arguments.

**Comment by GordStephen** [comment]
Yikes, that's what you get for not testing! Good catch.
