### ISSUE TITLE
seed() for RA v.0.5.0

### ISSUE THREAD

**Issue by juliebuard** [NREL/ResourceAdequacy.jl#44]
is the seed() working for ResourceAdequacy.jl v.0.5.0.
The runs seem to be very sensitive to sempling.  Being able to replicate the run could allow to benchmarch the running time in a simpler way.

**Comment by GordStephen** [comment]
Yes, seeding is currently not working in `master`, although it will be before v0.5.0 is tagged in the registry.

In this new version RNG seeding happens at the individual simulation level (or it will, once it's implemented), which will make seeded results consistent across machines using different numbers of threads, an improvement over 0.4. Unfortunately Julia's built-in Mersenne Twister RNG can't efficiently create that many seeded RNG instances, so we need to switch to another method (probably one of the [Random123 generators](https://dl.acm.org/doi/10.1145/2063384.2063405)) to do this instead.

For now, simulations just use the current global RNG associated with the thread they're running on, but with work stealing in Julia 1.3 we can no longer guarantee simulations will run on the same thread when `assess` is re-run, so results aren't currently reproducible.

**Comment by GordStephen** [comment]
Closed in https://github.com/NREL/PRAS/commit/40f9bcaac41cc2af65dabe605076075e4e456784
